name: Deploy para EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do c√≥digo-fonte
      uses: actions/checkout@v2

    - name: Copiar arquivos para o servidor EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: .
        target: /home/ubuntu/API_Figio

    - name: SSH para o servidor EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |

          cd /home/ubuntu/API_Figio
          sudo cp /home/ubuntu/cert.pem /home/ubuntu/API_Figio/src/
          sudo cp /home/ubuntu/key.pem /home/ubuntu/API_Figio/src/
          sudo pm2 delete API_Figio
          yarn
          sudo docker-compose up -d
          sudo ufw allow 3333/tcp
          sudo ufw allow 3333/udp
          yarn typeorm migration:run
          pm2 start "sudo yarn dev" --name API_Figio
